import type { Metadata } from "next";
import { Geist, Geist_Mono, Poppins } from "next/font/google";
import "./globals.css";
import NavBar from "./ui/components/navbar";
import { inter, lusitana } from "./ui/fonts";
import { ClerkProvider } from "@clerk/nextjs";
import { ChatbotProvider } from "./lib/chatbotContext";
import { WebSocketProvider } from "./lib/wsContext";
import { AudioRecorderProvider } from "./lib/transcriptContext";
import Chatbot from "./ui/components/chatbot/chatbot";

export const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});
export const poppins = Poppins({
  variable: "--font-poppins",
  subsets: ["latin"],
  weight: ["500", "600", "700", "900"],
});

export const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Homepage",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider>
      <ChatbotProvider>
        <WebSocketProvider>
          <AudioRecorderProvider>
            <html lang="en">
              <body className={`${inter.className}  antialiased px-4`}>
                <NavBar />
                <div className="h-12 w-full bg-white"></div>
                {children}
                <Chatbot/>
              </body>
            </html>
          </AudioRecorderProvider>
        </WebSocketProvider>
      </ChatbotProvider>
    </ClerkProvider>
  );
}
